### ISSUE TITLE
V1 TODO list

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Florian-DELRIEU/Tabs-BattleGenerator#1]
## Main features
- [x] Sélection aléatoire de factions
- [x] Choisir le nombre de factions aléatoire
- [x] Permettre les doublons de factions (oui/non) 
- [x] Permettre les unités spéciales (oui/non)
- [x] Indiquer les points
- [ ] Écrire un texte dès le lancement du programme avec les options possibles
- [ ] Les options doivent être toutes modifiables (facilement) via un terminal 

# Additional features
- [ ] Permettre un nombre limité d'unités spéciales ?
- [ ] Interdire ou non certaines unités de factions
- [ ] Bonus en points selon les interdictions
- [ ] Sélectionner la Maps
- [ ] Permettre au joueur de posséder une unité
